// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaWFUV7_-tnBAVvy8N1ntFbwcZym5gtNE',
    appId: '1:606890958813:android:986f07bbc1d0b71762e034',
    messagingSenderId: '606890958813',
    projectId: 'learning-2025',
    storageBucket: 'learning-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz1q7y9qdrnLJ2n3bYJ4pe54LDi8Xk2JI',
    appId: '1:606890958813:ios:ffe86c9e6dbe34e662e034',
    messagingSenderId: '606890958813',
    projectId: 'learning-2025',
    storageBucket: 'learning-2025.firebasestorage.app',
    androidClientId: '606890958813-npld0gkb5cck0llps5h6vooms5bs2tvv.apps.googleusercontent.com',
    iosClientId: '606890958813-2ivfoaueoo9g8j4mebmto8ju43a11vh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.innoBoonInterview',
  );

}